### ISSUE TITLE
Docker limits

### ISSUE THREAD

**Issue by dejlek** [kodless/leek#34]
When I tried to run Leek with Redis as broker I got:
```
es01         | ERROR: [2] bootstrap checks failed
es01         | [1]: max file descriptors [1024] for elasticsearch process is too low, increase to at least [65535]
es01         | [2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
es01         | ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/es-docker-cluster.log
```
Seems like a good idea to modify the Docker compose file to specify sufficient ulimits for ES.

**Comment by dejlek** [comment]
Issue [1] got solved by adding the following to the docker-compose.yml:
```
  es01:
      ...
    ulimits:
      ...
      nofile:
        soft: 66000
        hard: 80000

```
Issue [2] got solved with `sudo sysctl -w vm.max_map_count=262144` (maybe we should have this in the docs).
